- platform: mqtt
  state_topic: '{{sensorInstall}}/{{sensorEquipment}}/{{sensorID}}/{{sensorNumber}}/read'
  name: '{{sensorName}}'
  unit_of_measurement: '%'
  value_template: '{{ value_json.{{sensorParseValue}} }}'